# image will be published to ghcr.io/<user>/<name>
name: ub-custom
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: akmods
    install:
        - v4l2loopback
        - VirtualBox
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/eddsalkield/swaylock-effects/repo/fedora-%OS_VERSION%/eddsalkield-swaylock-effects-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/kallepm/tuxedo-control-center/repo/fedora-%OS_VERSION%/kallepm-tuxedo-control-center-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/kallepm/tuxedo-drivers/repo/fedora-%OS_VERSION%/kallepm-tuxedo-drivers-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
    # gnome
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-user-theme
    # allgemein
    #  - libreoffice-calc
      - podman-compose
      - thunderbird
      - VirtualBox
      - virtualbox-guest-additions
      - akmod-VirtualBox
      - zsh
      - zsh-syntax-highlighting
      - lsd
      - system-config-printer
      - mscore-fonts
      - powertop
      - sshfs
      - pinta # Bild-Editor
      - firewall-config
#      - tuxedo-drivers
#      - kernel-devel
#      - tuxedo-control-center
    # Hyprland + Wayland
      - hyprland
      - hypridle
      - hyprlock
      - waybar
      #- waybar-git # enthaelt neusten Snapshot von waybar.
      - kitty
      - alacritty
      - wofi
      - rofi
      - dunst
      - xdg-desktop-portal-hyprland
      - polkit-gnome
      - brightnessctl
      - pavucontrol
      - blueman
      - NetworkManager-tui
      - swaybg
      - swayidle
#      - swaylock-effects
      - wlogout
      - wl-clipboard
      - swappy
      - fontawesome-fonts-all
      - libappindicator-gtk3
      - network-manager-applet
      - swaylock
      - strace # for debugging Keycloak integration
    # labwc
    #  - labwc
    #  - bemenu
    # sway
#      - sway
#      - nwg-shell
    # i3
#      - i3
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

  - type: default-flatpaks
    system:
      install:
        - com.visualstudio.code
        - org.keepassxc.KeePassXC
        - net.cozic.joplin_desktop
        - com.brave.Browser
        - com.google.Chrome
        - com.mattjakeman.ExtensionManager
        - com.discordapp.Discord
        - info.portfolio_performance.PortfolioPerformance
        - io.podman_desktop.PodmanDesktop

  - type: signing
